<?php

function cptui_register_my_cpts_evento() {
    $labels = array(
        "name" => 'Eventi',
        "singular_name" => 'Evento',
        "menu_name" => 'Eventi',
        "all_items" => 'Tutti gli Eventi',
        "add_new" => 'Aggiungi nuovo',
        "add_new_item" => 'Aggiungi nuovo Evento',
        "edit_item" => 'Modifica Evento',
        "new_item" => 'Nuovo Evento',
        "view_item" => 'Visualizza Evento',
        "search_items" => 'Cerca Evento',
        "not_found" => 'Nessun Evento trovato',
        );

    $args = array(
        "label" => 'Eventi',
        "labels" => $labels,
        "description" => "",
        "public" => true,
        "show_ui" => true,
        "show_in_rest" => true,
        "rest_base" => "",
        "has_archive" => true,
        "show_in_menu" => true,
        "exclude_from_search" => false,
        "capability_type" => "post",
        "map_meta_cap" => true,
        "hierarchical" => false,
        "rewrite" => array( "slug" => "evento", "with_front" => true ),
        "query_var" => true,
        "menu_position" => 6,"menu_icon" => "dashicons-calendar-alt",
        "supports" => array( "title", "editor", "thumbnail" ),
        "taxonomies" => array( "category" ),
    );
    register_post_type( "evento", $args );
}


class events {

    static function register_post_type() {
        add_action( 'init', 'cptui_register_my_cpts_evento' );
    }

    static function register_acf_info() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
	            'key' => 'group_5aab10a3e4cc7',
	            'title' => 'Info evento',
	            'fields' => array(
		            array(
			            'key' => 'field_5aab14ceda2fe',
			            'label' => '',
			            'name' => '',
			            'type' => 'group',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'layout' => 'table',
			            'sub_fields' => array(
				            array(
					            'key' => 'field_5aab10c04a08a',
					            'label' => 'Data inizio',
					            'name' => 'data',
					            'type' => 'date_picker',
					            'instructions' => '',
					            'required' => 0,
					            'conditional_logic' => 0,
					            'wrapper' => array(
						            'width' => '',
						            'class' => '',
						            'id' => '',
					            ),
					            'display_format' => 'd/m/Y',
					            'return_format' => 'Ymd',
					            'first_day' => 1,
				            ),
				            array(
					            'key' => 'field_5aab11ffbecc8',
					            'label' => 'Durata',
					            'name' => 'durata',
					            'type' => 'number',
					            'instructions' => '',
					            'required' => 0,
					            'conditional_logic' => 0,
					            'wrapper' => array(
						            'width' => '',
						            'class' => '',
						            'id' => '',
					            ),
					            'default_value' => '',
					            'placeholder' => '',
					            'prepend' => 'n° giorni',
					            'append' => '',
					            'min' => 1,
					            'max' => '',
					            'step' => '',
				            ),
				            array(
					            'key' => 'field_5aab11a9becc7',
					            'label' => 'Orari',
					            'name' => 'orari',
					            'type' => 'text',
					            'instructions' => '',
					            'required' => 0,
					            'conditional_logic' => 0,
					            'wrapper' => array(
						            'width' => '',
						            'class' => '',
						            'id' => '',
					            ),
					            'default_value' => '',
					            'placeholder' => '16:00 - 20:00',
					            'prepend' => '',
					            'append' => '',
					            'maxlength' => '',
				            ),
			            ),
		            ),
		            array(
			            'center_lat' => 38.1746219,
			            'center_lng' => 15.5508471,
			            'zoom' => 17,
			            'key' => 'field_6350003f7d9b0',
			            'label' => 'Luogo (NEW)',
			            'name' => 'luogo_new',
			            'aria-label' => '',
			            'type' => 'open_street_map',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'return_format' => 'raw',
			            'layers' => array(
				            0 => 'OpenStreetMap.Mapnik',
			            ),
			            'allow_map_layers' => 0,
			            'height' => 300,
			            'max_markers' => 1,
		            ),
		            array(
			            'key' => 'field_5aab1256becc9',
			            'label' => 'Luogo',
			            'name' => 'luogo',
			            'aria-label' => '',
			            'type' => 'google_map',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => 'hidden',
				            'id' => '',
			            ),
			            'center_lat' => '38.196926',
			            'center_lng' => '15.555581',
			            'zoom' => 17,
			            'height' => 300,
		            ),
		            array(
			            'key' => 'field_5aab1299becca',
			            'label' => 'Contributo',
			            'name' => 'contributo',
			            'type' => 'number',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'default_value' => 0,
			            'placeholder' => '',
			            'prepend' => '€',
			            'append' => '',
			            'min' => 0,
			            'max' => '',
			            'step' => '',
		            ),
		            array(
			            'key' => 'field_5aab163f90ed3',
			            'label' => 'Posti',
			            'name' => 'posti',
			            'type' => 'group',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'layout' => 'table',
			            'sub_fields' => array(
				            array(
					            'key' => 'field_5aab164f90ed4',
					            'label' => 'Totali',
					            'name' => 'totali',
					            'type' => 'number',
					            'instructions' => '',
					            'required' => 0,
					            'conditional_logic' => 0,
					            'wrapper' => array(
						            'width' => '',
						            'class' => '',
						            'id' => '',
					            ),
					            'default_value' => '',
					            'placeholder' => '',
					            'prepend' => '',
					            'append' => '',
					            'min' => 1,
					            'max' => '',
					            'step' => '',
				            ),
				            array(
					            'key' => 'field_5aab169690ed5',
					            'label' => 'Disponibili',
					            'name' => 'disponibili',
					            'type' => 'number',
					            'instructions' => '',
					            'required' => 0,
					            'conditional_logic' => 0,
					            'wrapper' => array(
						            'width' => '',
						            'class' => '',
						            'id' => '',
					            ),
					            'default_value' => '',
					            'placeholder' => '',
					            'prepend' => '',
					            'append' => '',
					            'min' => '0',
					            'max' => '',
					            'step' => '',
				            ),
			            ),
		            ),
		            array(
			            'key' => 'field_5aab18892819e',
			            'label' => 'Informazioni di contatto',
			            'name' => '',
			            'type' => 'accordion',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'open' => 0,
			            'multi_expand' => 1,
			            'endpoint' => 0,
		            ),
		            array(
			            'key' => 'field_5aab172990ed6',
			            'label' => '',
			            'name' => 'contatto',
			            'type' => 'group',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'layout' => 'table',
			            'sub_fields' => array(
				            array(
					            'key' => 'field_5aab186d2819d',
					            'label' => 'Nome',
					            'name' => 'nome',
					            'type' => 'text',
					            'instructions' => '',
					            'required' => 0,
					            'conditional_logic' => 0,
					            'wrapper' => array(
						            'width' => '',
						            'class' => '',
						            'id' => '',
					            ),
					            'default_value' => '',
					            'placeholder' => '',
					            'prepend' => '',
					            'append' => '',
					            'maxlength' => '',
				            ),
				            array(
					            'key' => 'field_5aab172990ed7',
					            'label' => 'Telefono',
					            'name' => 'tel',
					            'type' => 'text',
					            'instructions' => '',
					            'required' => 0,
					            'conditional_logic' => 0,
					            'wrapper' => array(
						            'width' => '',
						            'class' => '',
						            'id' => '',
					            ),
					            'default_value' => '',
					            'placeholder' => '',
					            'prepend' => '',
					            'append' => '',
					            'maxlength' => '',
				            ),
				            array(
					            'key' => 'field_5aab172990ed8',
					            'label' => 'Email',
					            'name' => 'email',
					            'type' => 'text',
					            'instructions' => '',
					            'required' => 0,
					            'conditional_logic' => 0,
					            'wrapper' => array(
						            'width' => '',
						            'class' => '',
						            'id' => '',
					            ),
					            'default_value' => '',
					            'placeholder' => '',
					            'prepend' => '',
					            'append' => '',
					            'maxlength' => '',
				            ),
			            ),
		            ),
	            ),
	            'location' => array(
		            array(
			            array(
				            'param' => 'post_type',
				            'operator' => '==',
				            'value' => 'evento',
			            ),
		            ),
	            ),
	            'menu_order' => 0,
	            'position' => 'acf_after_title',
	            'style' => 'default',
	            'label_placement' => 'top',
	            'instruction_placement' => 'label',
	            'hide_on_screen' => '',
	            'active' => 1,
	            'description' => '',
            ));
        endif;
    }

    static function register_acf_partecipants() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
	            'key' => 'group_5aab13336d720',
	            'title' => 'Soci partecipanti',
	            'fields' => array(
		            array(
			            'key' => 'field_5aab135c44f1b',
			            'label' => '',
			            'name' => 'partecipanti',
			            'type' => 'user',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'role' => '',
			            'allow_null' => 1,
			            'multiple' => 1,
			            'return_format' => 'array',
		            ),
	            ),
	            'location' => array(
		            array(
			            array(
				            'param' => 'post_type',
				            'operator' => '==',
				            'value' => 'evento',
			            ),
			            array(
				            'param' => 'current_user_role',
				            'operator' => '==',
				            'value' => 'administrator',
			            ),
		            ),
	            ),
	            'menu_order' => 0,
	            'position' => 'side',
	            'style' => 'default',
	            'label_placement' => 'top',
	            'instruction_placement' => 'label',
	            'hide_on_screen' => '',
	            'active' => 1,
	            'description' => '',
            ));
        endif;
    }
}
