<?php


class users {

    static function register_acf_info() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
	            'key' => 'group_5aabd4fd85467',
	            'title' => 'Info utente',
	            'fields' => array(
		            array(
			            'key' => 'field_5aabd5251d4e2',
			            'label' => 'Telefono',
			            'name' => 'telefono',
			            'type' => 'text',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'default_value' => '',
			            'placeholder' => '',
			            'prepend' => '',
			            'append' => '',
			            'maxlength' => '',
		            ),
		            array(
			            'key' => 'field_5aabd5081d4e1',
			            'label' => 'Residenza',
			            'name' => 'residenza',
			            'type' => 'text',
			            'instructions' => '',
			            'required' => 1,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'default_value' => '',
			            'placeholder' => '',
			            'prepend' => '',
			            'append' => '',
			            'maxlength' => '',
		            ),
		            array(
			            'key' => 'field_5aabd53b1d4e3',
			            'label' => 'Nato a',
			            'name' => 'nato_a',
			            'type' => 'text',
			            'instructions' => '',
			            'required' => 1,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'default_value' => '',
			            'placeholder' => '',
			            'prepend' => '',
			            'append' => '',
			            'maxlength' => '',
		            ),
		            array(
			            'key' => 'field_5aabd5571d4e4',
			            'label' => 'Nato il',
			            'name' => 'nato_il',
			            'type' => 'date_picker',
			            'instructions' => '',
			            'required' => 1,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'display_format' => 'd/m/Y',
			            'return_format' => 'Ymd',
			            'first_day' => 1,
		            ),
		            array(
			            'key' => 'field_5aabd5aa1d4e5',
			            'label' => 'Codice fiscale',
			            'name' => 'codice_fiscale',
			            'type' => 'text',
			            'instructions' => '',
			            'required' => 1,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'default_value' => '',
			            'placeholder' => '',
			            'prepend' => '',
			            'append' => '',
			            'maxlength' => 16,
		            ),
		            array(
			            'key' => 'field_5aabd5ed1d4e6',
			            'label' => 'Data registrazione',
			            'name' => 'data_registrazione',
			            'type' => 'date_picker',
			            'instructions' => '',
			            'required' => 1,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'display_format' => 'd/m/Y',
			            'return_format' => 'Ymd',
			            'first_day' => 1,
		            ),
		            array(
			            'key' => 'field_5aabd6141d4e7',
			            'label' => 'Numero tessera',
			            'name' => 'numero_tessera',
			            'type' => 'number',
			            'instructions' => '',
			            'required' => 1,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'default_value' => '',
			            'placeholder' => '',
			            'prepend' => '',
			            'append' => '',
			            'min' => '',
			            'max' => '',
			            'step' => '',
		            ),
		            array(
			            'key' => 'field_5aabd6671d4e8',
			            'label' => 'Scadenza tessera',
			            'name' => 'scadenza_tessera',
			            'type' => 'date_picker',
			            'instructions' => '',
			            'required' => 1,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'display_format' => 'd/m/Y',
			            'return_format' => 'Ymd',
			            'first_day' => 1,
		            ),
		            array(
			            'key' => 'field_5aabd6c31d4e9',
			            'label' => 'Crediti',
			            'name' => 'crediti',
			            'type' => 'number',
			            'instructions' => '',
			            'required' => 1,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'default_value' => 0,
			            'placeholder' => '',
			            'prepend' => '',
			            'append' => '',
			            'min' => '',
			            'max' => '',
			            'step' => '',
		            ),
		            array(
			            'key' => 'field_5aabd6db1d4ea',
			            'label' => 'Interessi',
			            'name' => 'interessi',
			            'type' => 'taxonomy',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'taxonomy' => 'post_tag',
			            'field_type' => 'multi_select',
			            'allow_null' => 1,
			            'add_term' => 0,
			            'save_terms' => 0,
			            'load_terms' => 0,
			            'return_format' => 'id',
			            'multiple' => 0,
		            ),
	            ),
	            'location' => array(
		            array(
			            array(
				            'param' => 'user_form',
				            'operator' => '==',
				            'value' => 'all',
			            ),
		            ),
	            ),
	            'menu_order' => 0,
	            'position' => 'normal',
	            'style' => 'default',
	            'label_placement' => 'top',
	            'instruction_placement' => 'label',
	            'hide_on_screen' => '',
	            'active' => 1,
	            'description' => '',
            ));
        endif;
    }

    static function register_acf_management() {
        if( function_exists('acf_add_local_field_group') ):
            acf_add_local_field_group(array(
	            'key' => 'group_5aabddf8867e1',
	            'title' => 'Amministrazione utente',
	            'fields' => array(
		            array(
			            'key' => 'field_5aabddfee2ad7',
			            'label' => 'Tipologia socio',
			            'name' => 'tipologia_socio',
			            'type' => 'radio',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'choices' => array(
				            'ordinario' => 'Ordinario',
				            'effettivo' => 'Effettivo',
				            'sostenitore' => 'Sostenitore',
			            ),
			            'allow_null' => 0,
			            'other_choice' => 0,
			            'save_other_choice' => 0,
			            'default_value' => 'ordinario',
			            'layout' => 'horizontal',
			            'return_format' => 'value',
		            ),
		            array(
			            'key' => 'field_5aabde69e2ad8',
			            'label' => 'Badges',
			            'name' => 'badges',
			            'type' => 'checkbox',
			            'instructions' => '',
			            'required' => 0,
			            'conditional_logic' => 0,
			            'wrapper' => array(
				            'width' => '',
				            'class' => '',
				            'id' => '',
			            ),
			            'choices' => array(
				            'lasercutter' => 'Laser Cutter',
				            'fdm3dprinter' => 'FDM 3D Printer',
				            'cncengraver' => 'CNC Engraver',
			            ),
			            'allow_custom' => 0,
			            'save_custom' => 0,
			            'default_value' => array(
			            ),
			            'layout' => 'horizontal',
			            'toggle' => 0,
			            'return_format' => 'value',
		            ),
	            ),
	            'location' => array(
		            array(
			            array(
				            'param' => 'user_form',
				            'operator' => '==',
				            'value' => 'all',
			            ),
			            array(
				            'param' => 'current_user_role',
				            'operator' => '==',
				            'value' => 'administrator',
			            ),
		            ),
	            ),
	            'menu_order' => 0,
	            'position' => 'normal',
	            'style' => 'default',
	            'label_placement' => 'top',
	            'instruction_placement' => 'label',
	            'hide_on_screen' => '',
	            'active' => 1,
	            'description' => '',
            ));
        endif;
    }
}
